# Generated by Django 3.2.4 on 2021-07-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='total_volume',
            new_name='volume',
        ),
    ]
